position = "top"
height = 0


# [[end]]
# type = "volume"
# [[start]]
# type = "niri/workspaces"
#
# [[start]]
# type = "custom"

  # [[start.bar]]
  # type = "button"
  # label = """

[[end]]
type = "clock"
format = "󰥔  %H:%M"

[[end]]
type = "custom"

#   [[end.bar]]
#   type = "button"
#   label = ""
#   on_click = "popup:toggle"
#   tooltip = "Power menu"

#   [[end.popup]]
#   type = "box"
#   orientation = "vertical"
#   widgets = [
#     { type = "button", label = "Shutdown", on_click = "!shutdown now" },
#     { type = "button", label = "Restart",  on_click = "!reboot" }
#   ]



