position = "top"
height = 0

# margin.top = 5
# margin.left = 16
# margin.right = 16

# [[start]]
# type = "workspaces"

# [[center]]

# [[end]]
# type = "network_manager"
# icon_size = 32

[[end]]
type = "volume"

[[end]]
type = "clock"
format = "󰥔  %H:%M"

[[end]]
type = "custom"

  [[end.bar]]
  type = "button"
  label = ""
  on_click = "popup:toggle"
  tooltip = "Power menu"

  [[end.popup]]
  type = "box"
  orientation = "vertical"
  widgets = [
    { type = "button", label = "Shutdown", on_click = "!shutdown now" },
    { type = "button", label = "Restart",  on_click = "!reboot" }
  ]
