[mgr]
prepend_keymap = [
  { on = "<A-i>", run = "arrow prev" },
  { on = "<A-k>", run = "arrow next" },
  { on = "<A-j>", run = "leave" },
  { on = "<A-l>", run = "enter" },
  { on = "l", run = "noop" },
  { on = "j", run = "noop" },
  { on = "k", run = "noop" },
  { on = "h", run = "noop" },
  { on = "<Enter>", run = "open" },
  { on = "!", run = 'shell "$SHELL" --block' },
]
