[mgr]
show_hidden = true
ratio = [ 0, 1, 2 ]

# [opener]
# bash = [
#   { run = "bash \"$1\"", desc = "Run with bash", for = "unix" },
# ]

# [open]
# rules = [
#   { name = "*.sh", use = "bash" },
#   { mime = "text/*", use = "text" },
#   { name = "*", use = "text" },
# ]
